version: '3.2'
services:
    kepler:
        image: ewout/kepler:latest
        restart: always
        environment:
            MYSQL_HOST: mariadb
            MYSQL_USER: kepler
            MYSQL_DATABASE: kepler
            MYSQL_PASSWORD: verysecret
            KEPLER_PORT: 12321
            KEPLER_RCON_PORT: 12309
        depends_on:
            - mariadb
        links:
            - mariadb
        expose:
            - "12321"
            - "12309"
        ports:
            - "12321:12321"

    matcha:
        image: ewout/matcha:latest
        restart: always
        environment:
            MYSQL_HOST: mariadb
            MYSQL_USER: kepler
            MYSQL_DATABASE: kepler
            MYSQL_PASSWORD: verysecret
            REDIS_HOST: redis
            REDIS_PORT: 6379
            KEPLER_INTERNAL_HOST: kepler
            KEPLER_EXTERNAL_HOST: oldhabbo.localhost
            KEPLER_RCON_PORT: 12309
        depends_on:
            - redis
        links:
            - redis
            - kepler
        expose:
            - "12316"
        ports:
            - "127.0.0.1:12316:12316"

    redis:
        image: redis:latest
        restart: always

    mariadb:
        image: mariadb:10.2.15
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: superverysecret
            MYSQL_DATABASE: kepler
            MYSQL_USER: kepler
            MYSQL_PASSWORD: verysecret
        ports:
            - "127.0.0.1:3307:3306"
