version: '3.2'
services:
    #tmp:
    #    image: busybox
    #    command: chmod -R 777 /tmp/docker
    #    volumes:
    #        - /tmp/docker/
    kepler:
        build:
            context: kepler
            dockerfile: Dockerfile
        image: quackster/kepler:latest
        restart: always
        environment:
            MYSQL_HOST: mariadb
            MYSQL_USER: kepler
            MYSQL_DATABASE: kepler
            MYSQL_PASSWORD: verysecret
        ports:
            - "12321:12321"
        expose:
            - "12321"
            - "12309"

    matcha:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: emansom/matcha:latest
        depends_on:
            - redis
        links:
            - redis
            - kepler
        restart: always
        sysctls:
            net.core.somaxconn: 1024
            net.ipv4.tcp_syncookies: 0
            net.core.somaxconn: 65536
        ulimits:
            nofile:
                soft: 20000
                hard: 40000
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        volumes:
            - ./public:/srv/http/matcha/public:ro
            - ./app:/srv/http/matcha/app:ro

    nginx:
        image: nginx:mainline
        restart: always
        ports:
            - "12316:80"
        volumes:
            - ./public:/srv/http/matcha/public:ro
            - ./app:/srv/http/matcha/app:ro
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./h5bp/h5bp:/etc/nginx/h5bp:ro
            - ./h5bp/mime.types:/etc/nginx/mime.types:ro
       
    redis:
        image: redis:latest
        restart: always
        sysctls:
            net.core.somaxconn: 1024
        #command: redis-server /etc/redis.conf
        #volumes:
        #    - /redis/redis.conf:/etc/redis.conf
        #volumes_from:
        #    - tmp
    mariadb:
        image: mariadb:10.2.15
        restart: always
        ports:
           - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: superverysecret
            MYSQL_DATABASE: kepler
            MYSQL_USER: kepler
            MYSQL_PASSWORD: verysecret
        volumes:
            - ./kepler/kepler.sql:/docker-entrypoint-initdb.d/kepler.sql
            - ./site.sql:/docker-entrypoint-initdb.d/site.sql
