version: '3.2'
services:
    kepler:
        image: ewout/kepler:0.1.1
        restart: always
        environment:
            MYSQL_HOST: mariadb
            MYSQL_USER: kepler
            MYSQL_DATABASE: kepler
            MYSQL_PASSWORD: verysecret
            KEPLER_PORT: 12321
            KEPLER_RCON_PORT: 12309
        depends_on:
            - mariadb
        links:
            - mariadb
        expose:
            - "12321"
            - "12309"
        ports:
            - "12321:12321"

    matcha:
        image: ewout/matcha:0.1.1
        restart: always
        environment:
            MYSQL_HOST: mariadb
            MYSQL_USER: kepler
            MYSQL_DATABASE: kepler
            MYSQL_PASSWORD: verysecret
            REDIS_HOST: redis
            REDIS_PORT: 6379
            KEPLER_INTERNAL_HOST: kepler
            KEPLER_EXTERNAL_HOST: beta.oldhabbo.com
            KEPLER_RCON_PORT: 12309
        depends_on:
            - redis
        links:
            - redis
            - kepler
        expose:
            - "12316"
        ports:
            - "127.0.0.1:12316:12316"

    redis:
        image: redis:4
        restart: always
        volumes:
            - redis-data:/data

    mariadb:
        image: mariadb:10
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: superverysecret
            MYSQL_DATABASE: kepler
            MYSQL_USER: kepler
            MYSQL_PASSWORD: verysecret
        volumes:
            - kepler-data:/var/lib/mysql
        ports:
            - "127.0.0.1:3307:3306"
volumes:
    kepler-data:
    redis-data:
